### ISSUE TITLE
error: file 'nixpkgs' was not found in the Nix search path

### ISSUE THREAD

**Issue by hodgeheg1110** [dukzcry/crap#4]
Keep getting 'error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)' on Arch Linux when trying to run the script.

**Comment by dukzcry** [comment]
@hodgeheg1110 
Show me the output of
`echo $NIX_PATH`

**Comment by dukzcry** [comment]
Closing as upstream issue. Report to https://github.com/nixos/nixpkgs
