### ISSUE TITLE
Upgrade kernel 4.14.98 to4.14.102  KDE 5.13.4 black screen

### ISSUE THREAD

**Issue by pirboazo** [dukzcry/crap#6]
Hello 
After upgrade Nixos 18.09 at last kernel 4.14.102 

KDE have black screen .

I found that in journalctl when igrep KDE.

Feb 22 18:26:57 nixospib xsession[920]: 2019-02-22T18:26:57 kde4breeze.upd: Found new update '5.0KDE4Breeze_2'
Feb 22 18:26:58 nixospib xsession[920]: powerdevil: Backend is ready, KDE Power Management system initialized
Feb 22 18:32:18 nixospib xsession[920]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*

Regards.
Pierre

**Comment by pirboazo** [comment]
Hi all
Thank to Samueldr :+1:   and Sphalerite :+1:  to have help me resolve the issue.

**reason : **
Mismatch between application install with nix-enx and KDE Plasma.

**solution :**
remove all app install with nix-env 
and install them  with configuration.nix.

Side Effect several application have keep an old link in KDE :-(

**Comment by dukzcry** [comment]
@pirboazo Cool :smile:
